Added small improvements.
devopsspiral/KubeLibrary pull request #101
Opened 2021-12-06 15:15 UTC by MarcinMaciaszek

Small improvements in library

I have updated setup.py reqs and library scope. SUITE scope make much more sense for this library. 

Fixes #no_issue

Before merge following needs to be applied:
- [ ] At least one example testcase added in testcases/ --
- [ ] Library Documentation regenerated according to [Generate docs](https://github.com/devopsspiral/KubeLibrary#generate-docs)
- [x] PR entry added in CHANGELOG.md in **In progress** section
- [ ] All new testcases tagged as **prerelease** along other tags to exclude it from execution until released on PyPI
- [ ] Coverage threshold increased in [.coveragerc](https://github.com/devopsspiral/KubeLibrary/blob/master/.coveragerc) if new coverage is higher than actual, see the lint-and-coverage step in CI
```
fail_under = 67
```

2021-12-08 13:56 UTC, MarcinMaciaszek commented
@Nilsty @m-wcislo could you please review this PR?

2021-12-09 18:40 UTC, m-wcislo requested changes
Nice work, I really like making it less messy! I've added some small comments.

2021-12-09 18:40 UTC, m-wcislo commented on .circleci/config.yml
> +      - run:
We could use https://circleci.com/developer/orbs/orb/circleci/python?version=0.3.2#commands-install-deps with specified file name

2021-12-09 18:40 UTC, m-wcislo commented on CHANGELOG.md
> +- Refactored setup.py and requirements
Please keep it as one line with link to PR and author

2021-12-09 18:40 UTC, m-wcislo commented on src/KubeLibrary/version.py
> +version = "0.6.1"
we can keep it as 0.6.0, it is incremented just before release.

2021-12-14 12:17 UTC, m-wcislo approved these changes

2021-12-14 12:18 UTC, merged