Generate keyword documentation without a kubernetes cluster
devopsspiral/KubeLibrary pull request #103
Opened 2022-01-05 14:30 UTC by bli74

For a Docker image with Robotframework and additional
libraries we generate the keyword documentation for all
included Robot libraries with robotframework-hub-static
and robotframework-hub-bli.

For this a generic way to run libdoc is necessary and
library specific initialization would break the generic
approach.

So far robotframework-kubelibrary was the only library
where the generation of keyword documentation failed
and required access to a Kubernetes cluster.

This patch evaluates environment variable INIT_FOR_LIBDOC_ONLY.
When this variable is set to 1, the keyword documentation can
be created without the need to access a cluster.

2022-01-14 09:29 UTC, m-wcislo commented
Do you need PYPI release for the fix, or is it based on github branch?

2022-01-14 09:31 UTC, m-wcislo requested changes

2022-01-17 11:21 UTC, bli74 commented on src/KubeLibrary/KubeLibrary.py
> +        - INIT_FOR_LIBDOC_ONLY:
The description in README.md is updated

2022-01-18 07:01 UTC, frale98 approved these changes

2022-01-20 07:07 UTC, m-wcislo-eis approved these changes

2022-01-20 07:09 UTC, m-wcislo approved these changes

2022-01-20 07:10 UTC, merged

2022-01-26 15:27 UTC, frale98 commented
@m-wcislo we need a PYPI release please.